pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
    filePath: 'build/build.ps1'
    workingDirectory: 'build/'
    pwsh: true
- task: CopyFiles@2
  inputs:
    SourceFolder: 'build/publish/'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'site'
    publishLocation: 'Container'